version: 2
updates:
  - package-ecosystem: "npm" # This is the right setting for Yarn, go figure :)
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns:
          - "*"
