name: Monitoring tests

on:
  workflow_dispatch:
  schedule:
    - cron: 15 * * * * # every hour on the 15. minute

jobs:
  build:
    env:
      SECRETS_SET: ${{ secrets.SECRETS_SET }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run monitoring tests
        if: ${{ env.SECRETS_SET != '' }}
        run: yarn test:monitor
