name: Send Notifications

on:
  schedule:
    - cron: "25 7 * * *" # Run at 7.25 UTC each day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SHASUM_SECRET: ${{ secrets.SHASUM_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Install deps and run
        run: |
          yarn install
          ./bin/send-role-notifications.ts
