name: Test on Windows

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

env:
  DATA_SOURCE_LOCAL: yes

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        # We’d like to test the latest version & the version used on Vercel
        node-version: [16.x, 17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn config set network-timeout 600000 -g
      - run: yarn install
      - run: yarn test
      - run: yarn build
